1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [20]:
# Write a Python Program to Add Two Matrices?
import numpy as np
mat1=np.matrix([[1,2,3],[1,3,5],[5,6,7]])
mat2=np.matrix([[1,2,8],[2,3,4],[10,6,7]])
print("Result matrix after addition")
print("-----------------------------------------------")
print(mat1+mat2)

Result matrix after addition
-----------------------------------------------
[[ 2  4 11]
 [ 3  6  9]
 [15 12 14]]


In [21]:
# Write a Python Program to Multiply Two Matrices?
print("Result matrix after multiplication ")
print("-----------------------------------------------")
print(mat1*mat2)

Result matrix after multiplication 
-----------------------------------------------
[[ 35  26  37]
 [ 57  41  55]
 [ 87  70 113]]


In [11]:
#Write a Python Program to Transpose a Matrix?
print("Original matrix")
print(mat1)
print("-------------------------------------------------")
print("Matrix after transpose")
print(mat1.transpose())

Original matrix
[[1 2 3]
 [1 3 5]
 [5 6 7]]
-------------------------------------------------
Matrix after transpose
[[1 1 5]
 [2 3 6]
 [3 5 7]]


In [38]:
# Write a Python Program to Sort Words in Alphabetic Order?
str1="india is my conutry"
l=str1.split()
l.sort()
for i in l:
    print(i)

conutry
india
is
my


In [44]:
# Write a Python Program to Remove Punctuation From a String?
str1="india@ is#$% )_ my co*untry"
specialChars='''~!@#$%^&*()_{}[];:'"\/<>.?'-'''
for i in str1:
    if i in specialChars:
        str1=str1.replace(i,"")
str1

'india is  my country'